# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Tromboned' do
  pod 'Mixpanel'
end

target 'TrombonedTests' do

end

target 'Quick Fail' do

end

